version: '3'
services:
  db:
    image: mysql
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
      MYSQL_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 3300:3300