version: '3'
services:
  db:
    image: mysql
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tini
      MYSQL_USER: tinisv
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5